# Generated by Django 3.0.10 on 2020-10-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='image to classification', upload_to='', verbose_name='image')),
                ('status', models.CharField(choices=[('pending', 'waiting for processing'), ('processing', 'processing in progress'), ('done', 'processing is done')], default='pending', max_length=16, verbose_name='status')),
                ('label', models.CharField(help_text='label the image was classified with', max_length=255, verbose_name='label')),
            ],
            options={
                'verbose_name': 'inference',
                'verbose_name_plural': 'inferences',
            },
        ),
    ]
