version: '3'

volumes:
  local_postgres_data: { }
  local_postgres_data_backups: { }

services:
  tensorflow-serving:
    image: 'tensorflow/serving'
    ports:
      - '8500:8500'
      - '8501:8501'
    volumes:
      - '/tmp/model-data:/models'
    entrypoint:
      - '/usr/bin/tf_serving_entrypoint.sh'
      - '--model_config_file=/models/models.config'
      - '--model_config_file_poll_wait_seconds=10'


  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: moon_vision_challenge_local_django
    container_name: django
    depends_on:
      - postgres
      - tensorflow-serving
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: moon_vision_challenge_production_postgres
    container_name: postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres

  redis:
    image: redis:5.0
    container_name: redis

  celeryworker:
    <<: *django
    image: moon_vision_challenge_local_celeryworker
    container_name: celeryworker
    depends_on:
      - redis
      - postgres

    ports: [ ]
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: moon_vision_challenge_local_celerybeat
    container_name: celerybeat
    depends_on:
      - redis
      - postgres

    ports: [ ]
    command: /start-celerybeat

  flower:
    <<: *django
    image: moon_vision_challenge_local_flower
    container_name: flower
    ports:
      - "5555:5555"
    command: /start-flower
